#print('-----------------------------')
#print('      SISTEMA DE ALUNOS      ')
#print('-----------------------------')
#print('-----------------------------')
#print('   CADASTRO DE FUNCIONARIOS  ')
#print('-----------------------------')
#print('-----------------------------')
#print('      ERRO DE SISTEMA        ')
#print('-----------------------------')

def mostra_linha():
    print('-' * 30)

    
mostra_linha()   
print('      ALUIZIO        ')
mostra_linha()
mostra_linha()    
print('   APRENDENDO PYTHON  ')
mostra_linha()
mostra_linha()    
print('    PARA O TRABALHO ')
mostra_linha()  